site_name: Karned Rekipe Project Roadmap
site_description: Project roadmap and planning documentation for Karned Rekipe
site_author: Karned Team
site_url: https://karned-rekipe.github.io/roadmap/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - autorefs

nav:
  - Home: index.md
  - Roadmap:
    - Overview: roadmap/overview.md
    - To Do: roadmap/todo.md
    - In Progress: roadmap/in-progress.md
    - Completed: roadmap/completed.md
  - Development:
    - Contributing: development/contributing.md
    - GitHub Pages: development/github-pages.md
